# -*- coding: utf-8 -*-
"""Hackathon

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_55yWGCgRI-Nq93K-9b5ikgoAkK6yev6
"""

# --- INSTALLATION BLOCK ---
# Installing essential libraries for Computer Vision, OCR, and GenAI
!pip uninstall -y google-generativeai
!pip install -q google-generativeai==0.7.2 easyocr opencv-python-headless pandas matplotlib

import cv2
import easyocr
import numpy as np
import pandas as pd
import google.generativeai as genai
import matplotlib.pyplot as plt
import json
import os

GOOGLE_API_KEY = "YOUR_API_KEY_HERE"

genai.configure(api_key=GOOGLE_API_KEY)

model = genai.GenerativeModel("gemini-2.5-flash-lite")

print("Gemini connected")

!pip install -q google-generativeai==0.7.2

response = model.generate_content("Say hello")
print(response.text)

reader = easyocr.Reader(['en'], gpu=False)
print("✅ OCR ready")

def preprocess_receipt_image(image_path):
    img = cv2.imread(image_path)

    if img is None:
        raise Exception("Image not found")

    gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
    blur = cv2.GaussianBlur(gray, (5,5), 0)

    thresh = cv2.adaptiveThreshold(
        blur,255,
        cv2.ADAPTIVE_THRESH_GAUSSIAN_C,
        cv2.THRESH_BINARY,
        11,2
    )

    return img, thresh

def show_images(original, processed):
    plt.figure(figsize=(10,5))

    plt.subplot(1,2,1)
    plt.title("Original")
    plt.imshow(cv2.cvtColor(original, cv2.COLOR_BGR2RGB))
    plt.axis("off")

    plt.subplot(1,2,2)
    plt.title("Processed")
    plt.imshow(processed, cmap="gray")
    plt.axis("off")

    plt.show()

def parse_with_llm(raw_text):

    prompt = f"""
You are a receipt data extractor AI.

Extract items from this OCR text:
{raw_text}

Return ONLY JSON like:
[
{{"item":"milk","price":2.5,"quantity":1,"category":"dairy"}}
]
"""

    response = model.generate_content(prompt)
    text = response.text.strip()

    text = text.replace("```json","").replace("```","")

    try:
        data = json.loads(text)
        return data
    except:
        print("LLM JSON error")
        return []

def analyze_spending(data):

    if not data:
        print("No data")
        return

    df = pd.DataFrame(data)

    total = df["price"].sum()
    print("\n💰 TOTAL SPENT:", total)

    print("\n📊 CATEGORY BREAKDOWN:")
    print(df.groupby("category")["price"].sum())

    return df

def get_ai_advice(df):

    prompt = f"""
You are a financial advisor.

Spending data:
{df.to_dict(orient='records')}

Give short saving advice.
"""

    response = model.generate_content(prompt)
    print("\n💡 AI ADVICE:\n")
    print(response.text)

def run_receipt_ai(image_path):

    print("STEP 1: Processing image")
    original, processed = preprocess_receipt_image(image_path)
    show_images(original, processed)

    print("STEP 2: OCR")
    raw_text = extract_text(processed)
    print("\nOCR TEXT:\n", raw_text[:300])

    print("\nSTEP 3: LLM parsing")
    data = parse_with_llm(raw_text)

    print("\nExtracted Data:")
    print(data)

    print("\nSTEP 4: Analysis")
    df = analyze_spending(data)

    print("\nSTEP 5: Advice")
    get_ai_advice(df)

from google.colab import files
uploaded = files.upload()

IMAGE_PATH = list(uploaded.keys())[0]
run_receipt_ai(IMAGE_PATH)